services:
  backend:
    image: backend
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./backend/src:/app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
  frontend:
    image: frontend
    command: python -m http.server 3000
    volumes:
      - ./frontend/src:/app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  webappA2:
    image: pyapp
    command: python -m http.server 3000
    build: .
    ports:
      - "3000:3000"